import type { AnatomyPart } from "./types";

export const doublePendulumAnatomy: Record<number, AnatomyPart[]> = {
  12: [
    {
      tex: String.raw`\ddot{\theta}_1`,
      label: "Upper acceleration",
      meaning: "The jolt the integrator recomputes every RK4 tick as the arms flail.",
      value: "45",
      unit: "rad/s²",
    },
    { tex: " = ", glue: true },
    {
      tex: "f_1",
      label: "Coupling function",
      meaning: "The Lagrangian’s recipe mixing both angles and both rates into that jolt.",
      value: "45",
      unit: "rad/s²",
    },
    { tex: "(", glue: true },
    {
      tex: String.raw`\theta_1`,
      label: "Upper angle",
      meaning: "The main pendulum’s first rod, measured from vertical.",
      value: "0.6",
      unit: "rad",
    },
    { tex: ",", glue: true },
    {
      tex: String.raw`\theta_2`,
      label: "Lower angle",
      meaning: "The second rod’s lean relative to the first bob.",
      value: "−1.2",
      unit: "rad",
    },
    { tex: ",", glue: true },
    {
      tex: String.raw`\omega_1`,
      label: "Upper rate",
      meaning: "How fast the upper rod sweeps at this instant.",
      value: "2.5",
      unit: "rad/s",
    },
    { tex: ",", glue: true },
    {
      tex: String.raw`\omega_2`,
      label: "Lower rate",
      meaning: "The elbow’s whip, sharpest right as the ghost twin tears away.",
      value: "−3.8",
      unit: "rad/s",
    },
    { tex: ")", glue: true },
  ],
  13: [
    {
      tex: String.raw`\delta\theta(t)`,
      label: "Twin separation",
      meaning: "The gap between the amber tip and its cyan ghost twin on the canvas.",
      value: "1.0×10⁻³",
      unit: "rad",
    },
    { tex: String.raw` \sim `, glue: true },
    {
      tex: String.raw`e^{\lambda t}`,
      label: "Exponential blow-up",
      meaning: "At λ ≈ 2.3 per second the twin separates a thousandfold in about three seconds of tracking.",
      value: "2.3",
      unit: "s⁻¹",
    },
  ],
  14: [
    {
      tex: "E",
      label: "Total energy",
      meaning: "The conserved total whose drift would betray the integrator’s accuracy in the readout.",
      value: "−4.12",
      unit: "J",
    },
    { tex: " = ", glue: true },
    {
      tex: String.raw`\tfrac{1}{2}ml^2`,
      label: "Common prefactor",
      meaning: "Both bobs share mass 1 kg and length 1 m, so one factor scales the whole bracket.",
      value: "0.5",
      unit: "kg·m²",
    },
    { tex: String.raw`\left(`, glue: true },
    {
      tex: String.raw`2\omega_1^2`,
      label: "Upper-arm kinetic",
      meaning: "Doubled because both rods pivot from the first bob’s motion.",
      value: "12.5",
      unit: "s⁻²",
    },
    { tex: " + ", glue: true },
    {
      tex: String.raw`\omega_2^2`,
      label: "Elbow kinetic",
      meaning: "The lower bob’s own spin share of the kinetic budget.",
      value: "14.44",
      unit: "s⁻²",
    },
    { tex: " + ", glue: true },
    {
      tex: String.raw`2\omega_1\omega_2\cos(\theta_1-\theta_2)`,
      label: "Correlation kinetic",
      meaning: "Turns negative when the rods counter-swing, trimming the total.",
      value: "4.32",
      unit: "s⁻²",
    },
    { tex: String.raw`\right)`, glue: true },
    { tex: " - ", glue: true },
    {
      tex: String.raw`mgl\,(2\cos\theta_1 + \cos\theta_2)`,
      label: "Potential well",
      meaning: "Height of both bobs against gravity, deepest when both rods hang straight down.",
      value: "19.75",
      unit: "J",
    },
  ],
};
