import type { AnatomyPart } from "./types";

export const threeBodyAnatomy: Record<number, AnatomyPart[]> = {
  46: [
    {
      tex: String.raw`\ddot{x}`,
      label: "Horizontal tug",
      meaning: "The sideways pull bending your dragged mote off its straight launch line.",
      value: "1.2",
      unit: "units/s²",
    },
    { tex: " = ", glue: true },
    {
      tex: String.raw`2\dot{y}`,
      label: "Coriolis sideways",
      meaning: "A phantom push felt only while the mote moves across the spinning frame.",
      value: "0.7",
      unit: "units/s²",
    },
    { tex: " + ", glue: true },
    {
      tex: String.raw`\Omega_x`,
      label: "Potential slope x",
      meaning: "The downhill direction of the orange effective-potential floor at the mote’s spot.",
      value: "0.5",
      unit: "units/s²",
    },
    { tex: ",", glue: true },
    { tex: String.raw`\quad `, glue: true },
    {
      tex: String.raw`\ddot{y}`,
      label: "Vertical tug",
      meaning: "The companion steering term along the frame’s other axis.",
      value: "−0.5",
      unit: "units/s²",
    },
    { tex: " = ", glue: true },
    { tex: "-", glue: true },
    {
      tex: String.raw`2\dot{x}`,
      label: "Coriolis return",
      meaning: "The mirror Coriolis kick, flipping sign with the crossing direction.",
      value: "0.8",
      unit: "units/s²",
    },
    { tex: " + ", glue: true },
    {
      tex: String.raw`\Omega_y`,
      label: "Potential slope y",
      meaning: "The floor’s tilt along y, flattening near the five Lagrange markers.",
      value: "0.3",
      unit: "units/s²",
    },
  ],
  47: [
    {
      tex: "C",
      label: "Jacobi constant",
      meaning: "The number stamped on your launched mote that no chaotic path may ever rewrite.",
      value: "2.54",
      unit: "units²/s²",
    },
    { tex: " = ", glue: true },
    {
      tex: String.raw`2\Omega`,
      label: "Twice the potential",
      meaning: "Double the effective-floor height where the mote sits between the two suns.",
      value: "3.34",
      unit: "units²/s²",
    },
    { tex: " - ", glue: true },
    {
      tex: "v^2",
      label: "Speed squared",
      meaning: "Your drag length dialled in as launch speed, deducted forever after.",
      value: "0.8",
      unit: "units²/s²",
    },
  ],
  48: [
    {
      tex: String.raw`\Omega`,
      label: "Effective potential",
      meaning: "The orange floor whose twin wells trap orbits around each sun.",
      value: "1.67",
      unit: "units²/s²",
    },
    { tex: " = ", glue: true },
    {
      tex: String.raw`\frac{1-\mu}{r_1}`,
      label: "Big primary well",
      meaning: "Depth of the heavier sun’s grip, with “Mass ratio μ” parked at 0.12 and r₁ ≈ 1.41.",
      value: "0.62",
      unit: "units²/s²",
    },
    { tex: " + ", glue: true },
    {
      tex: String.raw`\frac{\mu}{r_2}`,
      label: "Small primary well",
      meaning: "The lighter companion’s hold — small, yet decisive near its Lagrange necks at r₂ ≈ 0.59.",
      value: "0.2",
      unit: "units²/s²",
    },
    { tex: " + ", glue: true },
    {
      tex: String.raw`\tfrac{1}{2}n^2(x^2+y^2)`,
      label: "Centrifugal bowl",
      meaning: "The rim that flings slow motes outward at large radii like (1.2, 0.5).",
      value: "0.85",
      unit: "units²/s²",
    },
  ],
};
